run_name: agnews_openai_0shot
task: classification
dataset:
  name: ag_news
  split: test[:200]
  text_field: text
  label_field: label
labels: ["World", "Sports", "Business", "Sci/Tech"]
prompt:
  system: |
    You are a precise news classifier. Return only one of the given categories.
  user_template: |
    Classify the news into one of the following categories:
    {labels}
    ---
    News: "{text}"
    Answer:
  shots: 0
model:
  backend: openai
  model_name: gpt-4o-mini
  temperature: 0.0
  max_tokens: 20
evaluation:
  metrics: ["accuracy", "f1_macro"]
  normalize_labels: true
seed: 42
batch_size: 4
